export const books = [
  {
    id: 1,
    title: 'Dark Roads: A Novel',
    author: 'Chevy Stevens',
    genre:'romance',
    year:1999,
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit quisquam aliquid, cum tempora repellat iusto.',
    likes: 99,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 2,
    title: 'Fellowship Point: A Novel',
    author: 'Alice Dark',
    genre:'novel',
    year:1999,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum enim culpa tempore qui ab placeat!',
    likes: 534,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 3,
    title: 'It All Comes Down to This',
    author: 'Therese Fowler',
    genre:'romance',
    year:1999,
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In itaque eius deserunt pariatur doloremque.',
    likes: 486,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 4,
    title: 'Lapvona: A Novel',
    author: 'Ottessa Mosh',
    genre:'romance',
    year:1929,
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum repellat maiores placeat quam.',
    likes: 21,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 5,
    title: 'joan',
    author: 'J.Chen',
    genre:'novel',
    year:1859,
    description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. A temporibus error sed debitis architecto quisquam!',
    likes: 213,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 6,
    title: 'Body Grammar',
    author: 'Jules Ohman',
    genre:'fiction',
    year:1999,
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo nesciunt eaque mollitia voluptates officia nulla.',
    likes: 234,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 7,
    title: 'Nightcrawling',
    author: 'Leila Mottley',
    genre:'romance',
    year:2000,
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ut corrupti obcaecati repellendus fuga!',
    likes: 653,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 8,
    title: 'Vacationland',
    author: 'Meg Mitchell',
    genre:'fiction',
    year:1999,
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim laboriosam dicta ipsa!',
    likes: 857,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 9,
    title: 'book1',
    author: 'author1',
    genre:'fiction',
    year:1995,
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta error numquam labore dicta aperiam voluptates',
    likes: 0,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 10,
    title: 'book2',
    author: 'author2',
    genre:'novel',
    year:1979,
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta error numquam labore dicta aperiam voluptates',
    likes: 0,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 11,
    title: 'book3',
    author: 'author3',
    genre:'fiction',
    year:1944,
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta error numquam labore dicta aperiam voluptates',
    likes: 0,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 12,
    title: 'book4',
    author: 'author4',
    genre:'romance',
    year:1999,
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta error numquam labore dicta aperiam voluptates',
    likes: 0,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 13,
    title: 'book5',
    author: 'author5',
    genre:'novel',
    year:1934,
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta error numquam labore dicta aperiam voluptates',
    likes: 0,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 14,
    title: 'book6',
    author: 'author6',
    genre:'romance',
    year:1987,
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta error numquam labore dicta aperiam voluptates',
    likes: 0,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 15,
    title: 'book7',
    author: 'author7',
    genre:'novel',
    year:1999,
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta error numquam labore dicta aperiam voluptates',
    likes: 88,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 16,
    title: 'book8',
    author: 'author8',
    genre:'fiction',
    year:1999,
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta error numquam labore dicta aperiam voluptates',
    likes: 0,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 17,
    title: 'book9',
    author: 'author9',
    genre:'romance',
    year:1999,
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta error numquam labore dicta aperiam voluptates',
    likes: 0,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 18,
    title: 'book10',
    author: 'author10',
    genre:'romance',
    year:1999,
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta error numquam labore dicta aperiam voluptates',
    likes: 785,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 19,
    title: 'book11',
    author: 'author11',
    genre:'fiction',
    year:1999,
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta error numquam labore dicta aperiam voluptates',
    likes: 45,
    cover: 'https://picsum.photos/200/250',
  },
  {
    id: 20,
    title: 'book12',
    author: 'author12',
    genre:'romance',
    year:1999,
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta error numquam labore dicta aperiam voluptates',
    likes: 5,
    cover: 'https://picsum.photos/200/250',
  },

]